
SOURCES += \
        $$PWD/src/CBPBoxFactory/BPBoxFactory.cpp \
        $$PWD/src/CBPBoxManager/BluePrintPage.cpp \
        $$PWD/src/CBPStatic/BPStatic.cpp \
        $$PWD/src/CFlowConnectionLine/FlowConnectionLine.cpp \
        $$PWD/src/CIOTerminal/CInputTerminal/InputTerminal.cpp \
        $$PWD/src/CIOTerminal/COutputTerminal/OutputTerminal.cpp \
        $$PWD/src/CIOTerminal/IOTerminal.cpp \
        $$PWD/src/CBPBoxManager/BPBoxManager.cpp \
        $$PWD/src/COperationBox/BitwiseOperationBoxes/BitWiseAND.cpp \
        $$PWD/src/COperationBox/BitwiseOperationBoxes/BitWiseComplement.cpp \
        $$PWD/src/COperationBox/BitwiseOperationBoxes/BitWiseLeftShift.cpp \
        $$PWD/src/COperationBox/BitwiseOperationBoxes/BitWiseOR.cpp \
        $$PWD/src/COperationBox/BitwiseOperationBoxes/BitWiseRightShift.cpp \
        $$PWD/src/COperationBox/BitwiseOperationBoxes/BitWiseXOR.cpp \
        $$PWD/src/COperationBox/DataComparisonOperations/JsonParser.cpp \
        $$PWD/src/COperationBox/LoopsArrays/ArrayLength.cpp \
        $$PWD/src/COperationBox/LoopsArrays/FineInArray.cpp \
        $$PWD/src/COperationBox/LoopsArrays/GetByIndex.cpp \
        $$PWD/src/COperationBox/LoopsArrays/ParseIntoArray.cpp \
        $$PWD/src/COperationBox/LoopsArrays/ForEachLoop.cpp \
        $$PWD/src/COperationBox/Miscellaneous/BlueScriptBox.cpp \
        $$PWD/src/COperationBox/Miscellaneous/ConditionalBranch.cpp \
        $$PWD/src/COperationBox/Miscellaneous/DataCounter.cpp \
        $$PWD/src/COperationBox/DataComparisonOperations/DataComparisonEqual.cpp \
        $$PWD/src/COperationBox/DataComparisonOperations/DataComparisonGreater.cpp \
        $$PWD/src/COperationBox/DataComparisonOperations/DataComparisonLess.cpp \
        $$PWD/src/COperationBox/Miscellaneous/DelayMakerBox.cpp \
        $$PWD/src/COperationBox/Miscellaneous/StopWatch.cpp \
        $$PWD/src/COperationBox/dataSinkBoxes/FileSink.cpp \
        $$PWD/src/COperationBox/dataSinkBoxes/LiveDataXYModel.cpp \
        $$PWD/src/COperationBox/dataSinkBoxes/LineSeriesChartBox.cpp \
        $$PWD/src/COperationBox/LogicalOperationBoxes/LogicalAND.cpp \
        $$PWD/src/COperationBox/LogicalOperationBoxes/LogicalNOT.cpp \
        $$PWD/src/COperationBox/LogicalOperationBoxes/LogicalOR.cpp \
        $$PWD/src/COperationBox/MathOperationBoxes/MathAbsolute.cpp \
        $$PWD/src/COperationBox/MathOperationBoxes/MathAddition.cpp \
        $$PWD/src/COperationBox/MathOperationBoxes/MathDivision.cpp \
        $$PWD/src/COperationBox/MathOperationBoxes/MathModulo.cpp \
        $$PWD/src/COperationBox/MathOperationBoxes/MathMultiplication.cpp \
        $$PWD/src/COperationBox/MathOperationBoxes/MathPower.cpp \
        $$PWD/src/COperationBox/MathOperationBoxes/MathSubtraction.cpp \
        $$PWD/src/COperationBox/dataSinkBoxes/CSocketClientSink.cpp \
        $$PWD/src/COperationBox/dataSinkBoxes/StringOutputSink.cpp \
        $$PWD/src/COperationBox/dataSourceBoxes/ButtonSource.cpp \
        $$PWD/src/COperationBox/dataSourceBoxes/FileSource.cpp \
        $$PWD/src/COperationBox/dataSourceBoxes/HTTPBase.cpp \
        $$PWD/src/COperationBox/dataSourceBoxes/HTTPGetter.cpp \
        $$PWD/src/COperationBox/dataSourceBoxes/HTTPPoster.cpp \
        $$PWD/src/COperationBox/dataSourceBoxes/TCPSocketServerSource.cpp \
        $$PWD/src/COperationBox/dataSourceBoxes/TimerSendValSrc.cpp \
        $$PWD/src/COperationBox/dataSourceBoxes/UDPSocketServerSource.cpp \
        $$PWD/src/COperationBox/Miscellaneous/UniversalTypeConvertor.cpp \
        $$PWD/src/COperationBox/OperationBox.cpp \
        $$PWD/src/CRawValueBase/RawValueBase.cpp \
        $$PWD/src/CRawValueBase/Value_array.cpp



HEADERS += \
    $$PWD/src/CBPBoxFactory/BPBoxFactory.h \
    $$PWD/src/CBPBoxManager/BluePrintPage.h \
    $$PWD/src/CBPStatic/BPStatic.h \
    $$PWD/src/CFlowConnectionLine/FlowConnectionLine.h \
    $$PWD/src/CIOTerminal/CInputTerminal/InputTerminal.h \
    $$PWD/src/CIOTerminal/COutputTerminal/OutputTerminal.h \
    $$PWD/src/CIOTerminal/IOTerminal.h \
    $$PWD/src/CBPBoxManager/BPBoxManager.h \
    $$PWD/src/COperationBox/BitwiseOperationBoxes/BitWiseAND.h \
    $$PWD/src/COperationBox/BitwiseOperationBoxes/BitWiseComplement.h \
    $$PWD/src/COperationBox/BitwiseOperationBoxes/BitWiseLeftShift.h \
    $$PWD/src/COperationBox/BitwiseOperationBoxes/BitWiseOR.h \
    $$PWD/src/COperationBox/BitwiseOperationBoxes/BitWiseRightShift.h \
    $$PWD/src/COperationBox/BitwiseOperationBoxes/BitWiseXOR.h \
    $$PWD/src/COperationBox/DataComparisonOperations/JsonParser.h \
    $$PWD/src/COperationBox/LoopsArrays/ArrayLength.h \
    $$PWD/src/COperationBox/LoopsArrays/FineInArray.h \
    $$PWD/src/COperationBox/LoopsArrays/GetByIndex.h \
    $$PWD/src/COperationBox/LoopsArrays/ParseIntoArray.h \
    $$PWD/src/COperationBox/LoopsArrays/ForEachLoop.h \
    $$PWD/src/COperationBox/Miscellaneous/BlueScriptBox.h \
    $$PWD/src/COperationBox/Miscellaneous/ConditionalBranch.h \
    $$PWD/src/COperationBox/Miscellaneous/DataCounter.h \
    $$PWD/src/COperationBox/DataComparisonOperations/DataComparisonEqual.h \
    $$PWD/src/COperationBox/DataComparisonOperations/DataComparisonGreater.h \
    $$PWD/src/COperationBox/DataComparisonOperations/DataComparisonLess.h \
    $$PWD/src/COperationBox/Miscellaneous/DelayMakerBox.h \
    $$PWD/src/COperationBox/Miscellaneous/StopWatch.h \
    $$PWD/src/COperationBox/dataSinkBoxes/FileSink.h \
    $$PWD/src/COperationBox/dataSinkBoxes/LiveDataXYModel.h \
    $$PWD/src/COperationBox/dataSinkBoxes/LineSeriesChartBox.h \
    $$PWD/src/COperationBox/LogicalOperationBoxes/LogicalAND.h \
    $$PWD/src/COperationBox/LogicalOperationBoxes/LogicalNOT.h \
    $$PWD/src/COperationBox/LogicalOperationBoxes/LogicalOR.h \
    $$PWD/src/COperationBox/MathOperationBoxes/MathAbsolute.h \
    $$PWD/src/COperationBox/MathOperationBoxes/MathAddition.h \
    $$PWD/src/COperationBox/MathOperationBoxes/MathDivision.h \
    $$PWD/src/COperationBox/MathOperationBoxes/MathModulo.h \
    $$PWD/src/COperationBox/MathOperationBoxes/MathMultiplication.h \
    $$PWD/src/COperationBox/MathOperationBoxes/MathPower.h \
    $$PWD/src/COperationBox/MathOperationBoxes/MathSubtraction.h \
    $$PWD/src/COperationBox/dataSinkBoxes/CSocketClientSink.h \
    $$PWD/src/COperationBox/dataSinkBoxes/StringOutputSink.h \
    $$PWD/src/COperationBox/dataSourceBoxes/ButtonSource.h \
    $$PWD/src/COperationBox/dataSourceBoxes/FileSource.h \
    $$PWD/src/COperationBox/dataSourceBoxes/HTTPBase.h \
    $$PWD/src/COperationBox/dataSourceBoxes/HTTPGetter.h \
    $$PWD/src/COperationBox/dataSourceBoxes/HTTPPoster.h \
    $$PWD/src/COperationBox/dataSourceBoxes/TCPSocketServerSource.h \
    $$PWD/src/COperationBox/dataSourceBoxes/TimerSendValSrc.h \
    $$PWD/src/COperationBox/dataSourceBoxes/UDPSocketServerSource.h \
    $$PWD/src/COperationBox/Miscellaneous/UniversalTypeConvertor.h \
    $$PWD/src/COperationBox/OperationBox.h \
    $$PWD/src/CommonHeader.h \
    $$PWD/src/CRawValueBase/RawValueBase.h
