qt_add_qml_module(QBluePrint
    URI "org.QBluePrint.Boxes"
    VERSION 1.0
    SOURCES

    ${CMAKE_CURRENT_LIST_DIR}/../src/CBPBoxFactory/BPBoxFactory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/CBPBoxManager/BPBoxManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/OperationBox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/BitwiseOperationBoxes/BitWiseAND.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/BitwiseOperationBoxes/BitWiseComplement.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/BitwiseOperationBoxes/BitWiseLeftShift.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/BitwiseOperationBoxes/BitWiseOR.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/BitwiseOperationBoxes/BitWiseRightShift.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/BitwiseOperationBoxes/BitWiseXOR.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/DataComparisonOperations/JsonParser.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/LoopsArrays/ArrayLength.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/LoopsArrays/FineInArray.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/LoopsArrays/GetByIndex.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/LoopsArrays/ParseIntoArray.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/LoopsArrays/ForEachLoop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/Miscellaneous/BlueScriptBox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/Miscellaneous/ConditionalBranch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/Miscellaneous/DataCounter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/DataComparisonOperations/DataComparisonEqual.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/DataComparisonOperations/DataComparisonGreater.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/DataComparisonOperations/DataComparisonLess.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/Miscellaneous/DelayMakerBox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/Miscellaneous/StopWatch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSinkBoxes/FileSink.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSinkBoxes/LiveDataXYModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSinkBoxes/LineSeriesChartBox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/LogicalOperationBoxes/LogicalAND.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/LogicalOperationBoxes/LogicalNOT.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/LogicalOperationBoxes/LogicalOR.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/MathOperationBoxes/MathAbsolute.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/MathOperationBoxes/MathAddition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/MathOperationBoxes/MathDivision.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/MathOperationBoxes/MathModulo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/MathOperationBoxes/MathMultiplication.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/MathOperationBoxes/MathPower.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/MathOperationBoxes/MathSubtraction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSinkBoxes/CSocketClientSink.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSinkBoxes/StringOutputSink.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSourceBoxes/ButtonSource.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSourceBoxes/FileSource.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSourceBoxes/HTTPBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSourceBoxes/HTTPGetter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSourceBoxes/HTTPPoster.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSourceBoxes/TCPSocketServerSource.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSourceBoxes/TimerSendValSrc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSourceBoxes/UDPSocketServerSource.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/Miscellaneous/UniversalTypeConvertor.cpp

    ${CMAKE_CURRENT_LIST_DIR}/../src/CBPBoxFactory/BPBoxFactory.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/CBPBoxManager/BPBoxManager.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/OperationBox.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/BitwiseOperationBoxes/BitWiseAND.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/BitwiseOperationBoxes/BitWiseComplement.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/BitwiseOperationBoxes/BitWiseLeftShift.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/BitwiseOperationBoxes/BitWiseOR.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/BitwiseOperationBoxes/BitWiseRightShift.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/BitwiseOperationBoxes/BitWiseXOR.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/DataComparisonOperations/JsonParser.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/LoopsArrays/ArrayLength.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/LoopsArrays/FineInArray.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/LoopsArrays/GetByIndex.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/LoopsArrays/ParseIntoArray.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/LoopsArrays/ForEachLoop.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/Miscellaneous/BlueScriptBox.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/Miscellaneous/ConditionalBranch.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/Miscellaneous/DataCounter.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/DataComparisonOperations/DataComparisonEqual.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/DataComparisonOperations/DataComparisonGreater.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/DataComparisonOperations/DataComparisonLess.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/Miscellaneous/DelayMakerBox.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/Miscellaneous/StopWatch.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSinkBoxes/FileSink.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSinkBoxes/LiveDataXYModel.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSinkBoxes/LineSeriesChartBox.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/LogicalOperationBoxes/LogicalAND.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/LogicalOperationBoxes/LogicalNOT.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/LogicalOperationBoxes/LogicalOR.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/MathOperationBoxes/MathAbsolute.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/MathOperationBoxes/MathAddition.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/MathOperationBoxes/MathDivision.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/MathOperationBoxes/MathModulo.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/MathOperationBoxes/MathMultiplication.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/MathOperationBoxes/MathPower.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/MathOperationBoxes/MathSubtraction.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSinkBoxes/CSocketClientSink.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSinkBoxes/StringOutputSink.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSourceBoxes/ButtonSource.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSourceBoxes/FileSource.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSourceBoxes/HTTPBase.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSourceBoxes/HTTPGetter.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSourceBoxes/HTTPPoster.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSourceBoxes/TCPSocketServerSource.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSourceBoxes/TimerSendValSrc.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/dataSourceBoxes/UDPSocketServerSource.h
    ${CMAKE_CURRENT_LIST_DIR}/../src/COperationBox/Miscellaneous/UniversalTypeConvertor.h
)
